import { Box, Flex, Code } from '@chakra-ui/react';
import Link from 'next/link';

import { SEO_DATA, VERCEL_LOGO } from 'src/constants';
import { NextPageWithLayout } from 'src/models';
import { Image, SEO, Text, Title } from 'src/components';

import styles from 'src/styles/Home.module.css';

const Home: NextPageWithLayout = (): JSX.Element => {
  return (
    <>
      {/* <Head>
        <title>NextJS Examples</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head> */}

      <SEO data={SEO_DATA} />

      <Box as="main" className={styles.main}>
        <Text className={styles.title} fontFamily="subBody">
          Welcome to{' '}
          <Link href="https://nextjs.org" target="_blank">
            Next.js!
          </Link>
        </Text>

        <Text textStyle="description">
          Get started by editing <Code className={styles.code}>pages/index.tsx</Code>
        </Text>

        <Box className={styles.grid}>
          <Link href="https://nextjs.org/docs" target="_blank" className={styles.card}>
            <Title>Documentation &rarr;</Title>
            <Text>Find in-depth information about Next.js features and API.</Text>
          </Link>

          <Link href="https://nextjs.org/learn" target="_blank" className={styles.card}>
            <Title>Learn &rarr;</Title>
            <Text>Learn about Next.js in an interactive course with quizzes!</Text>
          </Link>

          <Link
            href="https://github.com/vercel/next.js/tree/canary/examples"
            target="_blank"
            className={styles.card}
          >
            <Title>Examples &rarr;</Title>
            <Text>Discover and deploy boilerplate example Next.js projects.</Text>
          </Link>

          <Link
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <Title>Deploy &rarr;</Title>
            <Text>Instantly deploy your Next.js site to a public URL with Vercel.</Text>
          </Link>
        </Box>
      </Box>

      <Flex as="footer" justify="center" align="center">
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <Image {...VERCEL_LOGO} display="inline-block" />
        </Link>
      </Flex>
    </>
  );
};

export default Home;
